package Ejercicio2;
import becker.robots.*;

public class main {
    public static void main (String[] args)
	{
		City Bogota = new City();
                numeros R = new numeros();
                        
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                R.girarDerecha();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();          
                R.validar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarIzquierda();
                R.girarIzquierda();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                System.out.println("numero oculto del primer cajon: " + R.getNumeroOculto() );
                R.girarIzquierda();
                R.avanzar();
                R.avanzar();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                R.girarDerecha();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();          
                R.validar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarIzquierda();
                R.girarIzquierda();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                System.out.println("numero oculto del segundo cajon: " + R.getNumeroOculto2() );
                R.girarIzquierda();
                R.avanzar();
                R.avanzar();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                R.girarDerecha();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();
                R.validar();
                R.avanzar();          
                R.validar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarIzquierda();
                R.girarIzquierda();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.avanzar();
                R.girarDerecha();
                R.avanzar();
                R.girarIzquierda();
                R.avanzar();
                System.out.println("numero oculto del tercer cajon: " + R.getNumeroOculto3() );
              }    
    
}
