package Ejercicio6;
public class main {
    public static void main (String []args){
        ladrillos rob = new ladrillos();
        rob.avanzar();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.girarDerecha();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.girarDerecha();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.girarDerecha();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        rob.avanzar();
        rob.recoger();
        rob.avanzar();
        //
        rob.girarIzquierda();
        rob.avanzar();
        rob.girarIzquierda();
        for(int i=1; i<7; i++){
            rob.avanzar();
        }
        rob.girarIzquierda();
        for(int i=1; i<4; i++){
            rob.avanzar();
        }
        //
        rob.avanzar();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.girarDerecha();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.girarDerecha();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.girarDerecha();
        rob.avanzar();
        rob.colocar();
        rob.avanzar();
        rob.avanzar();
        rob.colocar();
        //
        rob.avanzar();
        rob.girarIzquierda();
        rob.avanzar();
        rob.girarIzquierda();
        rob.avanzar();
    }
}